### ISSUE TITLE
tests: fix python 3.8 issue on travis

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/marshmallow-utils#2]
Package version (if known): v0.1.1

## Describe the bug

Test fails due to pytest-pycodestyle apparently having an issue on Python 3.8.
Locally tests on Python 3.8 pass.

**Comment by ppanero** [comment]
Closing this since the CI in GH Actions is running properly in Py 3.8, @lnielsen feel free to re-open if needed.
