### ISSUE TITLE
strip_html should leave space between block elements

### ISSUE THREAD

**Issue by dfdan** [inveniosoftware/marshmallow-utils#54]
Package version (if known): all

## Describe the bug

When strip_html is passed string containing multiple paragaphs (eg by rdm-records' ui serialiser), entries with multiple paragraphs are concatenated without spacing. This looks poor and reduces readability. 

## Steps to Reproduce

See screenshots below (from Invenio RDM), or: 

```python
In [3]: strip_html('<p>a</p><p>b</p>')
Out[3]: 'ab'
```
## Expected behaviour

A single space should be inserted between the paragraphs content to ensure the stripped description is readable, ie:

```python
In [3]: strip_html('<p>a</p><p>b</p>')
Out[3]: 'a b'
```

## Screenshots (if applicable)
Invenio RDM record description with 2 paragraphs:
![Screenshot 2022-02-11 at 18 17 06](https://user-images.githubusercontent.com/7934352/153673854-0726c8c0-55f8-47ee-b711-67010ef772e6.png)

Renders in search without space between paragraphs:
![Screenshot 2022-02-11 at 21 41 07](https://user-images.githubusercontent.com/7934352/153674156-2c393387-5c6f-483d-94dc-c652c3b10819.png)

## Additional context

I have made a local workaround that inserts a space after any paragraph closing tag before calling strip_html. Perhaps 
a proper fix would use html.parse to pass the description to strip_html 1 paragraph at a time? Happy to give that a go if it seems sensible.

**Comment by dfdan** [comment]
I've looked into this further - there is a known issue with bleach addressed by this PR: https://github.com/mozilla/bleach/pull/642

I've confirmed this fixes the issue, so we can just bump dependencies here if/when that PR merges.

**Comment by lnielsen** [comment]
Ok, then I'm closing the ticket since we'll get it in automatically with the latest bleach.
